export const ACHIEVEMENT_DEFINITIONS = [
  {
    key: "first_session",
    title: "First Step",
    description: "Complete your first focus session",
    icon: "🎯",
  },
  {
    key: "streak_3",
    title: "3-Day Streak",
    description: "Focus 3 days in a row",
    icon: "🔥",
  },
  {
    key: "streak_7",
    title: "Week Warrior",
    description: "Focus 7 days in a row",
    icon: "⚡",
  },
  {
    key: "streak_30",
    title: "Unstoppable",
    description: "Focus 30 days in a row",
    icon: "🏆",
  },
  {
    key: "hours_10",
    title: "10 Hours In",
    description: "Accumulate 10 total focused hours",
    icon: "⏱️",
  },
  {
    key: "hours_50",
    title: "50 Hours Deep",
    description: "Accumulate 50 total focused hours",
    icon: "💎",
  },
  {
    key: "zero_distraction",
    title: "Laser Focus",
    description: "Complete a session with zero distractions",
    icon: "🎯",
  },
  {
    key: "night_owl",
    title: "Night Owl",
    description: "Complete a session after 10pm",
    icon: "🦉",
  },
  {
    key: "early_bird",
    title: "Early Bird",
    description: "Complete a session before 7am",
    icon: "🌅",
  },
  {
    key: "sessions_10",
    title: "Getting Started",
    description: "Complete 10 focus sessions",
    icon: "🌱",
  },
  {
    key: "sessions_50",
    title: "Half Century",
    description: "Complete 50 focus sessions",
    icon: "🌿",
  },
  {
    key: "sessions_100",
    title: "Centurion",
    description: "Complete 100 focus sessions",
    icon: "🌳",
  },
  {
    key: "long_session",
    title: "Deep Diver",
    description: "Complete a single session of 60+ minutes",
    icon: "🤿",
  },
  {
    key: "weekend_warrior",
    title: "Weekend Warrior",
    description: "Complete a session on both Saturday and Sunday of the same week",
    icon: "🛡️",
  },
  {
    key: "skill_master",
    title: "Skill Mastery",
    description: "Reach a skill's target hours goal",
    icon: "👑",
  },
  {
    key: "explorer",
    title: "Explorer",
    description: "Complete sessions across 3 or more different skills",
    icon: "🧭",
  },
  {
    key: "comeback",
    title: "The Comeback",
    description: "Rebuild your streak to 7 days after a reset",
    icon: "💪",
  },
  {
    key: "resisted_temptation",
    title: "Stayed the Course",
    description: "Chose to keep focusing instead of stopping early, 5 times",
    icon: "🧘",
  },
] as const
